---
  - name: "Creating docker containers"
    hosts: localhost
    connection: local 
    tasks:

    - name: "installing docker-compose"
      shell: "apt install docker-compose"
      register: "output"


    - name: "executing docker compose"
      shell: "docker-compose up -d"
      register: "output"

    - debug: var=output.stdout_lines
